---
title: "Fear and loathing in Conway, NH"
author: "Michael DiDomenico"
date: 2018-08-18
categories: ["Life"]
tags: ["Memoir"]
---


# Born to lose

## Bachelor party here we come

My buddy John typifies what I expect a Mainer should be like. He is laid back and loves the simple pleasures in life, especially being out in nature. He has a lot of the same kinds of personality traits that I have, maybe beause I am from Colorado.

John was getting married, and for his bachelor party, he wanted to take a couple of buddies canoeing down the Saco River. This was nothing out of the ordinary for him. He took this trip for several years with some of his buddies, but it was the first time I was going to get to go. I assume we were going to have a nice weekend with a little beer drinking, a little nature, and some good old fashioned male bonding. What I wasn't expecting was any sort of trouble or really much excitement for that manner. I was expecting the laid back nature trip.

## Meeting the boys

I flew into Boston and was meeting up with my buddy Hiren. He took an earlier flight but it turns out he was delayed, so I was able to meet up with him laying over at La Guardia.

"Hey, Hiren. How's it going."
"Ah you know. Still trying to get a seat on the next flight, but the board isn't working. I should be first on the list."

So we decided to wait a bit. Everything as usual was a big mess in front of the gate with everyone standing, inching closer to the front, making sure that whenever something hapened they would be the first to take advantage. I ran to the restroom and grabbed a steat.

"Looks like they're starting to board"
"I've got a while. I didn't even know borading groups went up to 6!"

Over the loudspeaker, the gate captain said the flight was overbooked and they asked for a volunteer to give up his or her seat for $300. Hiren hadn't been confirmed for a seat, so I went up and said, "You can get me on the next train, right?" "Yes." "Okay, sign me up." "okay. We may not need you. Just grab a seat, and I will check in with you in a bit."

It turns out she checked in with Hiren first to confirm his seat. Now it was looking like Hiren would be on my flight and I would be waiting. At least I was getting $300! And he was going to have to wait in Boston for me before he could go anyway. Turns out they sneake me on the very last seat, last row. It wasn't in the bathroom, but I had a farily good handle on what was going on in there.

## Maybe we can canoe to the river

## So that's what the back of a police car feels like

Some of the other guys had brought up some fireworks to set off in celebration of John getting married. We were thinking we could set them off in the parking space of the airbnb where we were staying, but the owner told us that the little boy living there had a seizure condition and that we should find someplace else. A couple of the boys scouted out a location to shoot off the fireworks and said they had it all worked out.

At some point maybe shortly before midnight, they told us it was time, and I thought, sure fireworks are fun. We started walking down the road, then they had us cross down a road that led to a canoe rental place. We kept going until we were beside a big field and set down everything thinking it was a nice clearing for viewing the show. It was a nice, clear sky, and me and another guy got out our starmaps to identify some of the planets and stars we could see.

After a few minutes of setting up, we started lighting some stuff. The fireworks were pretty good, but the mortars were very loud. There were maybe 36 in the package and we had a few boxes, some roman candles, and some lame M-80 knockoffs. 

Just before we were done with the last of it, we saw some headlights coming down the road towards us. The car cut its lights, and someone said, "Let's get out of here!" We didn't really run so much as walk across the field to the other side, and hoped whoever it was wouldn't find us. We were pretty sure it was the cops, but there were no flashing lights or anything like that. 

These guys were the worst hiders in history! One of them still had his phone flashlight on, which we had been using to see the fireworks to light them. Another one of us kept talking about how we would be okay and no one was going to come looking for us over some fireworks that aren't illegal. I was trying to keep quiet and scan to see if anything was happening. I thought I caught a small light in the field a couple time coming around the perimeter. 

When he was about 15 feet away, the policeman flashed on his big maglight and told us to stop. Most of us were just standing there, but one guy tried to jump into the woods before the cop again told him to freeze. I had an empty bottle of Jamison and an empty beer in my hands behind my back and dropped them and took a couple steps forward. I was conflicted about the littering, but I figured it would maybe look worse to be double fisting.

The officer asked us why we were being so sketchy about fireworks, trying to run. We didn't really have much of an answer, but someone said that we weren't sure if it was one of the property owners, and we weren't sure what they would do. The cop seemed to be okay with that answer, and said something like, a mad property owner was likely to do something crazy. Then he marched us back to the fireworks and told us to pick up all the trash. I was thinking he was just going to have us pick everything up and let us go, but when we got back to the canoe rental building, there were a couple of other cops waiting. The rule someone once told me is if they bring a second cop car, you are going to jail.

The first cop got all of our names and lined us up and called in to check on any warrants. It took a few minutes, but he came back and said we were all clean. Then he said but we have you on criminal trespassing and a very clear case of disorderly conduct and that he was going to arrest us. 

I recently had been reading up on the Henry Gates incident because it had come up during a conversation, which is neither here nor there really, but one of the things that stuck out in the article was about how police like to use disorderly conduct as a catch all when it really wasn't intended for minor things. I thought, yep, that sounds like a bit of bullshit, but what are you going to do? 

We all waited and were handcuffed and were led off to various police cruisers to be taken in. The guy who cuffed me and rode me in was pretty nice. As we walked to his cruiser, I noticed the first car we passes had "Supervisor" painted on it, so I assume the guy who came into the field to find us was the shift supervisor. As we walked, he asked me if I had been in much trouble. I said that I was actually a squeaky clean guy. He told me not to worry to much, that they would probably release us on a citation like a speeding ticket. He put me in the back of his Explorer. It was a little difficult getting in being cuffed, but also because the seat was very close to the partition separating the front seat from the rear seat. The back seat itself was just hard plastic. I was surprised how uncomfortable it was trying to sit there with my hand behind me and the cuffs forcing my hands to stack up on each other. Later, one of the guys told me there was a cutout handcuff slot to make it easier. Oh well. I will be happy if I never have to think about that again. On the ride I chatted with the police officer. It turns out he was from northern Virginia and came up to Conway because it paid way better. It was a fairly normal ride with general chit chat. It was actually a bit surreal given my position.

When we got to the station they has us empty our pockets and took us into a large conference room to answer some questions, I think to see if it would be safe to throw us in a cell. After that, they marched me into the holding unit, told me to take off my flip flops and put me in a single cell. The cell itself was long and narrow, maybe about 6 feet wide and 12 feet deep. There was a cement pured bed with a vinyl covered pad on it and a grey wool blanket. At the back end was a toilet with no lid, no seat, and no way to flush it. I took a piss and laid out with the blanket over my face to see if I could get some rest, even if just a bit of mindfullness while waiting to see what was next. 

It quickly became apparent that rest would be difficult. First, they keep on the bright lights. I could kind of deal with that using the blanket. The more difficult part was the noise. It was very easy to hear between cells, and there was a woman who was making a lot of racket. And by a lot, I mean constant pounding on the door and shouting. She would yell, "Hello? Hello? I need some water." There were other variations about not having any right to lock her up. But mostly there were hellos and requests for water. I heard the shift supervisor go over to yell at her to shut up a couple of times. Once, she stopped for about 45 seconds, and my body started to relax a bit. Then she started up again. "Hello? Hello?" That went on constantly for the rest of the time we were in there.

After a couple of hours, I could hear the supervisor going to some of the other cells and telling the guys that they were going to give us a really good deal and let us off with a Commonwealth violation for tresspassing that is similar to a ticket. By the time he got to me, he asked if I heard him say it to others, and I said yes, and he said they would need to do a bit of paperwork and would have to find someone who could pick us up. I asked if we could walk, and he said no, because if we got hit on the side of the road it would come back on him. Sometime later he came back and said that someone was there to get us, but that he needed to breathalize us before he could release us. It was the first time I ever took a breathalizer. I think I blew a 0.009 or maybe it was a 0.09, who can remember. Either way, he said, "Not bad," and he walked me to the waiting room. Someone gave me my watch and cellphone, and I went outside into the lobby and saw a couple of friends there.

I was the first one out, and they were howling with laughter and were trying to take a video of us coming out. The girl at the desk seemed to be finding it all a bit funny too. I was just tired and ready to find some sleep.

## Piecing some things together

Meg used the tracker to find Bob and called the PD when she saw he was at the station.

Maybe government employment helped. Someone said they overheard the cops saying that they couldn't do anything to wreck our jobs.

Georgie was asleep on the couch. Niether the cop or him pretended he was going to be driving anywhere. Hiren was like I am ready to go, where is your car, and the cop was like, no you have to drive your own car. So he had Georgie wake up Al.

## (serious) Reflections